Features/movie details api
movielot/movielot-server pull request #7
Opened 2022-08-27 11:58 UTC by oopty

### 무엇에 관한 내용인가요?
영화 상세 정보 받아오기
  - TMDB에서 제공하는 기본 상세 정보
  - OTT 상영 여부
  - 예고편, 티저 등 관련 영상 정보
  - 평점 정보

### 무엇을 리뷰받기 원하나요?
1. DTO가 너무 많아요 관리할 방법을 모르겠음
2. 영화 상세 정보에 너무 많은 걸 집어 넣는게 아닌가?
3. JSON 응답이 아래와 같이 나오는데 맞는지 확인
```json
{
    "message": "success",
    "contents": {
        "adult": false,
        "backdrop_path": "/rr7E0NoGKxvbkb89eR1GwfoYjpA.jpg",
        "genres": [
            {
                "id": 18,
                "name": "드라마"
            }
        ],
        "id": 550,
        "original_language": "en",
        "original_title": "Fight Club",
        "overview": "자동차 회사의 리콜 심사관으로 일하는 주인공(에드워드 노튼)은 일상의 무료함과 공허함 속에서 늘 새로운 탈출을 꿈꾼다. 그는 비행기에서 자신을 비누 제조업자라고 소개하는 타일러 더든(브래드 피트)을 만난다. 집에 돌아온 주인공은 아파트가 누군가에 의해 폭파되었음을 발견하고, 타일러에게 도움을 청해 함께 생활하게 된다. 어느 날 밤 타일러는 주인공에게 자신을 때려달라고 부탁한다. 사람은 싸워봐야 진정한 자신을 알 수 있다는 것이다. 결국 이들은 매주 토요일 밤 술집 지하에서 맨주먹으로 격투를 벌이는 파이트 클럽을 결성하기에 이르는데...",
        "popularity": 100.276,
        "poster_path": "/eKZ07Ted7VHxQjbuZrRBFOamcKJ.jpg",
        "release_date": "1999-10-15",
        "title": "파이트 클럽",
        "video": false,
        "vote_average": 8.431,
        "vote_count": 24659,
        "videos": {
            "id": 550,
            "results": [
                {
                    "name": "파이트클럽(Fight Club, 1999)_메인예고편_PLAYY",
                    "key": "2EKUbAKFYg0",
                    "site": "YouTube",
                    "size": 1080,
                    "type": "Trailer",
                    "official": false,
                    "id": "600d1abb22e480003f02dcbe"
                }
            ]
        },
        "providers": {
            "id": 550,
            "results": {
                "KR": {
                    "link": "https://www.themoviedb.org/movie/550-fight-club/watch?locale=KR",
                    "buy": [
                        {
                            "displayPriority": 0,
                            "logoPath": null,
                            "providerName": null,
                            "providerId": 0
                        },
                        {
                            "displayPriority": 0,
                            "logoPath": null,
                            "providerName": null,
                            "providerId": 0
                        }
                    ],
                    "rent": null,
                    "flatrate": [
                        {
                            "displayPriority": 0,
                            "logoPath": null,
                            "providerName": null,
                            "providerId": 0
                        },
                        {
                            "displayPriority": 0,
                            "logoPath": null,
                            "providerName": null,
                            "providerId": 0
                        },
                        {
                            "displayPriority": 0,
                            "logoPath": null,
                            "providerName": null,
                            "providerId": 0
                        }
                    ]
                }
            }
        },
        "rating": {
            "im_db_id": null,
            "title": "Fight Club",
            "full_title": null,
            "type": "Movie",
            "year": "1999",
            "im_db": null,
            "metacritic": "66",
            "the_movie_db": null,
            "rotten_tomatoes": null,
            "film_affinity": null,
            "error_message": null
        }
    }
}
```

### 테스트는 어떻게 하면 되나요?
아래 환경변수 설정하고 그냥 돌리면 되요

```
MONGODB_PASSWORD=movielot;MONGODB_ID=movielot;MONGODB_DATABASE=movielot;MONGODB_NODES=ac-7akkqfl-shard-00-00.kv6yjfl.mongodb.net:27017,ac-7akkqfl-shard-00-01.kv6yjfl.mongodb.net:27017,ac-7akkqfl-shard-00-02.kv6yjfl.mongodb.net:27017;TMDB_AUTH_KEY=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlMDg2YTc1OGY1OTZlNzRjNzE5YjUxYmEyZjAwOTUzYSIsInN1YiI6IjYyZGJjYTQzZWE4NGM3MDA0Y2RiMTRmNCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.HgyxaECbpFRd4PuNwveVVwxD6Rp_VuQbQHGXQVUN3aY;IMDB_AUTH_KEY=k_4wk6caxa
```

### 이슈 사항
X

2022-08-28 11:14 UTC, isangu requested changes
코멘트 + DTO 부분에 대한 Partial Response 구현은 조금 더 고민해보고 수정해봅시다~

2022-08-28 11:14 UTC, isangu commented on src/main/java/net/movielot/movielot/service/MovieService.java
> +        IMDBRatingResponse rating = imdbClient.getRating(details.getImdbId());
non blocking 코드로 개선할 수 있지 않을까여? (restTemplate -> WebClient)

2022-08-28 11:14 UTC, oopty commented
- 평점정보는 일단 비워놓음
- webClient로 바꾸기
- DTO를 exntends로 재활용하고  getGenreIds를 `@JacksonIgnore`로 무시 (`@JacksonView` 등등 알아보기)

2022-09-06 13:07 UTC, me-jsj approved these changes
snakecase 변환 잘봤습니다.^^

2022-09-07 01:39 UTC, isangu approved these changes

2022-09-07 02:11 UTC, merged